{% set python_min = '3.10' %}
{% set name = "datashaper" %}
{% set version = "0.0.49" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/datashaper-{{ version }}.tar.gz
  sha256: 05bfba5964474a62bdd5259ec3fa0173d01e365208b6a4aff4ea0e63096a7533

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - pip
  run:
    - python >={{ python_min }},<4.0
    - pandas >=2.2.0,<3.0.0
    - jsonschema >=4.21.1,<5.0.0
    - pyarrow >=15.0.0,<16.0.0
    - numpy <2,>=1.16.6  # the restriction is missing in pyarrow
    - diskcache >=5.6.3,<6.0.0

test:
  imports:
    - datashaper
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: This project provides a collection of utilities for doing lightweight data wrangling.
  home: https://github.com/microsoft/datashaper
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
